name 'eas-base'
maintainer 'opscale'
maintainer_email 'cookbooks@opscale.com'
license 'Apache 2.0'
description 'Installs/Configures eas-base'
long_description 'Installs/Configures eas-base'
version '0.1.4'

depends 'apt', '~> 2.6.0'
depends 'chef-solo-search', '~> 0.5.1'
depends 'users', '~> 1.7.0'
depends 'sudo', '~> 2.7.1'
depends 'postfix', '~> 3.6.0'
depends 'rsyslog', '~> 1.12.2'
depends 'route53', '~> 0.3.5'
# depends 'nagios', '~> 5.3.4'
