name             'eas-base'
maintainer       'opscale'
maintainer_email 'cookbooks@opscale.com'
license          'Apache 2.0'
description      'Installs/Configures eas-base'
long_description 'Installs/Configures eas-base'
version          '0.1.0'


depends 'apt'
depends 'chef-solo-search'
depends 'users'
depends 'sudo'
depends 'postfix'
depends 'rsyslog'
